# Generated by Django 5.2.7 on 2025-10-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('website_name', models.CharField(default="Vick's ChatBot", max_length=100, verbose_name='Website/App Name')),
                ('website_link', models.URLField(default='https://github.com/imvickykumar999/ADK-Django', max_length=255, verbose_name='Primary Website Link')),
                ('website_logo_url', models.URLField(default='https://avatars.githubusercontent.com/u/67197854', max_length=255, verbose_name='Logo URL')),
                ('theme_color', models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('purple', 'Purple'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('orange', 'Orange'), ('red', 'Red'), ('green', 'Green'), ('pink', 'Pink')], default='indigo', help_text='Select a base Tailwind color name for the application theme.', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
