# Generated by Django 5.2.7 on 2025-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='website_link',
            field=models.URLField(default='https://github.com/imvickykumar999/Custom-Chatbot', max_length=255, verbose_name='Primary Website Link'),
        ),
    ]
