# Generated by Django 5.2.7 on 2025-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapedDataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2048, unique=True, verbose_name="Source URL"
                    ),
                ),
                ("scraped_by_user_id", models.CharField(db_index=True, max_length=100)),
                (
                    "scrape_mode",
                    models.CharField(
                        choices=[("single", "Single Page"), ("sitemap", "Sitemap")],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="H1 Tag Content",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("content_summary", models.TextField(verbose_name="Content Snippet")),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scraped Data Entry",
                "verbose_name_plural": "Scraped Data Entries",
            },
        ),
    ]
