# Generated by Django 5.2.7 on 2025-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrapeddataentry",
            options={
                "ordering": ["-scraped_at"],
                "verbose_name": "Scraped Data Entry",
                "verbose_name_plural": "Scraped Data Entries",
            },
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="content_summary",
            field=models.TextField(
                blank=True, null=True, verbose_name="Content Summary (First 500 chars)"
            ),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name / H1"
            ),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="scrape_mode",
            field=models.CharField(
                choices=[("single", "Single Page"), ("sitemap", "Full Sitemap")],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="scraped_by_user_id",
            field=models.CharField(max_length=50, verbose_name="Scraped by user id"),
        ),
        migrations.AlterField(
            model_name="scrapeddataentry",
            name="url",
            field=models.URLField(
                max_length=2000, unique=True, verbose_name="Source URL"
            ),
        ),
    ]
