# Generated by Django 5.2.7 on 2025-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_scrapeddataentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddataentry',
            name='content_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Content Summary'),
        ),
    ]
